### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by reiz** [cstamas/maven-indexer-examples#4]
I just checked out this project, but I'm not able to build it. Getting this Exception:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.270 s
[INFO] Finished at: 2014-08-24T14:23:17+02:00
[INFO] Final Memory: 6M/265M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project indexer-example-01: Could not resolve dependencies for project org.apache.maven.indexer:indexer-example-01:jar:1.0.0-SNAPSHOT: Could not find artifact org.apache.maven.indexer:indexer-core:jar:6.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

On which repository is the indexer-core:jar:6.0-SNAPSHOT available?

**Comment by rdp** [comment]
I ran into this as well.  Any way to update the README to point to the "right" place as it were?

**Comment by carlspring** [comment]
@cstamas ,

Now that all this is actually in the [maven-indexer](https://github.com/apache/maven-indexer/tree/master/indexer-examples), would you mind removing this original repository, so that people don't get confused, or maybe add a link to point to the new location for the examples?

**Comment by carlspring** [comment]
@rdp,

The code is located in [indexer-examples](https://github.com/apache/maven-indexer/tree/master/indexer-examples) which is part of the [maven-indexer/](https://github.com/apache/maven-indexer/) repository. This is the correct indexer.

**Comment by rdp** [comment]
Yes a note in the README might help. so the "real" 6.0-SNAPSHOT should come
from apache/maven-indexer is that right? Thanks.

**Comment by cstamas** [comment]
Yup, will update README, sorry for the confusion folks!
